apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    owner: lakhonin
    description: web_server_for_site
spec:
  selector:
    project: myweb
  type: NodePort
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 8888
