Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update -y
  sudo apt install -y python3-pip
  sudo apt-get install -y python-dev postgresql-server-dev-all
  pip3 install psycopg2
  SHELL
  config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig"
end
