{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(probe_duration_seconds{})" }
   ]
  },
  {
   "title": "Uptime ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"node-exporter:9100\"} - node_boot_time_seconds{instance=~\"node-exporter:9100\"}"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - node_memory_MemFree_bytes{instance=~\"node-exporter:9100\"} / node_memory_MemTotal_bytes{instance=~\"node-exporter:9100\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"node-exporter:9100\"}[5m]))"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{} - time()"
    }
   ]
  },
  {
   "title": "HTTP Code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_http_status_code{}" }
   ]
  },
  {
   "title": "Disk free",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(node_filesystem_free_bytes{instance=~\"node-exporter:9100\"}) / sum(node_filesystem_size_bytes{instance=~\"node-exporter:9100\"}))"
    }
   ]
  }
 ]
}