- hosts: master
  gather_facts: false
  become: true
  become_user: root
  vars_files:
  - ssh_key_vault.yml
  
  tasks:
  - name: create user
    user:
      name: aleksandr
      state: present

  - name: create dir
    file: 
      path: /home/aleksandr/.ssh 
      state: directory 
      mode: '0700' 
      owner: aleksandr     

  - name: decode private key    
    shell: echo {{ssh_private_key}} |base64 --decode
    register: ssh_private_key_decoded

  - name: copy private key
    template: 
      src: HOME_.ssh_id_rsa
      dest: /home/aleksandr/.ssh/id_rsa
      mode: '0600' 
      owner: aleksandr

  - name: copy public key
    template: 
      src: HOME_.ssh_id_rsa.pub 
      dest: /home/aleksandr/.ssh/id_rsa.pub 
      mode: '0644' 
      owner: aleksandr
