- hosts: master
  become: yes
  remote_user: ubuntu
  become_user: root
  
    tasks:
     - name: Enable the MySQL service
       service:
        name: mysqld
        state: started
        enabled: true
